version: '2'
services:
  web:
    build: .
    volumes:
      - .:/code
      - logvolume01:/var/log
    expose:
      - "2222"
    ports:
      - "2225:2222"
    environment:
      VIRTUAL_HOST: favgam.seaknot.dev
      LETSENCRYPT_HOST: favgam.seaknot.dev
      LETSENCRYPT_EMAIL: toru-letsencrypt-favgam@torus.jp

volumes:
  logvolume01: {}

networks:
   default:
      external:
         name: seaknotweb_default
